# Module 2: Biogeochemistry {#M2_1 -}

<h2>Bacterially Mediated Organic Matter Oxidation Rates</h2>

### Objectives {#M2_2 -}
Become familiar with basic spread sheet commands in excel by building a simple biogeochemical model from chemical and mathematical equations. Become familiar with the program R Studio and compare it to Excel.

### Modelling concepts {#M2_3 -}
This model has variables of concentration and rate, no spatial dimensions, and it has a dimension of time. Last week’s model had variables of volume and concentration (salinity), and was also resolved in time. In coming weeks the models will be resolved in zero, one, two or three dimensions of space, and only some will be resolved in time. Going down the rows of the Excel spread sheet means going forward in time, as the differential equations break the time axis into hundreds of tiny little chunks. The concentration at any point in time may depend on concentration at the previous point in time. We use the notation concentrationt depends on concentration^t-1^.

### Organic matter oxidation {#M2_4 -}
Organic matter (dead algae, leaves etc.) is oxidised by different bacteria that use a range of oxidants. The bacteria simultaneously consume organic matter and an oxidant, in a similar way to how humans consume carbohydrate and oxygen. Scientists have observed that there is a general sequence of oxidants used, based on the energy available for each process. When all of the oxidants are consumed, methanogenesis takes place, where bacteria use the organic matter alone without any oxidant. This is similar to the lactic acid metabolic system that the human body uses when oxygen is in short supply, such as when you go for a run. Remember that methane is a reduced byproduct, not an oxidant. Other reduced by-products include N~2~ gas, Mn^2+^ and Fe^2+^ metal ions, and the S^2-^ anion.

We can construct a model to determine the rates at which the oxidation takes place, and use the rates to determine other processes such as oxygen consumption, denitrification or phosphate adsorption.

The rate is dependent on the concentration of the organic matter, $\color{#E36C0A}{OM}$, and a rate constant, $\color{#00B0F0}{k_{OM}}$. The rate is not dependent on the concentration of the oxidant, until the oxidant concentration becomes very low: this process is included as a $\color{#76923C}{\text{limitation}}$ term (With more O~2~ you do not become super; with less O~2~ you get sleepy). A $\color{#76923C}{\text{Monod}}$ equation is used to limit the rate.

<center>
<br>
\begin{equation}
R_{O_{2}} = \color{#00B0F0}{K_{OM}}\color{#E36C0A}{OM}\color{#76923C}{\frac{O_{2}}{O_{2}+K_{O_{2}}}}
(\#eq:module2-1)
\end{equation}
</center>
<br>

The generally observed sequence of oxidants is modelled with an $\color{#FF0000}{\text{inhibition}}$ process, so that a higher energy yielding oxidant, such as oxygen, inhibits a lower energy oxidant such as iron.

<center>
<br>
\begin{align*}
R_{NO_{3}} &= \color{#00B0F0}{k_{OM}}\color{#E36C0A}{OM}\color{#76923C}{\frac{NO_{3}}{NO_{3}+K_{NO_{3}}}}\color{#FF0000}{\frac{K_{O_{2}}}{O_{2}+K_{O_{2}}}}\\
(\#eq:module2-2)\\
R_{Mn} &= \color{#00B0F0}{k_{OM}}\color{#E36C0A}{OM}\color{#76923C}{\frac{Mn}{Mn+K_{Mn}}}\color{#FF0000}{\frac{K_{NO_{3}}}{NO_{3}+K_{NO_{3}}}}\color{#FF0000}{\frac{K_{O_{2}}}{O_{2}+K_{O_{2}}}}\\
(\#eq:module2-3)\\
R_{Fe} &= \color{#00B0F0}{k_{OM}}\color{#E36C0A}{OM}\color{#76923C}{\frac{Fe}{Fe+K_{Fe}}}\color{#FF0000}{\frac{K_{Mn}}{Mn+K_{Mn}}}\color{#FF0000}{\frac{K_{NO_{3}}}{NO_{3}+K_{NO_{3}}}}\color{#FF0000}{\frac{K_{O_{2}}}{O_{2}+K_{O_{2}}}}\\
(\#eq:module2-4)\\
R_{SO_{4}} &= \color{#00B0F0}{k_{OM}}\color{#E36C0A}{OM}\color{#76923C}{\frac{SO_{4}^{2-}}{SO_{4}^{2-}+K_{SO_{4}}}}\color{#FF0000}{\frac{K_{Fe}}{Fe+K_{Fe}}}\color{#FF0000}{\frac{K_{Mn}}{Mn+K_{Mn}}}\color{#FF0000}{\frac{K_{NO_{3}}}{NO_{3}+K_{NO_{3}}}}\color{#FF0000}{\frac{K_{O_{2}}}{O_{2}+K_{O_{2}}}}\\
(\#eq:module2-5)\\
R_{Meth} &= \color{#00B0F0}{k_{OM}}\color{#E36C0A}{OM}\color{#FF0000}{\frac{K_{SO_{4}}}{SO_{4}^{2-}+K_{SO_{4}}}}\color{#FF0000}{\frac{K_{Fe}}{Fe+K_{Fe}}}\color{#FF0000}{\frac{K_{Mn}}{Mn+K_{Mn}}}\color{#FF0000}{\frac{K_{NO_{3}}}{NO_{3}+K_{NO_{3}}}}\color{#FF0000}{\frac{K_{O_{2}}}{O_{2}+K_{O_{2}}}}\\
(\#eq:module2-6)\\
\end{align*}
</center>
<br>

In this lab, we simulate a blob of aquatic sediment. It is a closed system, so that the initial concentrations react until they reach equilibrium. This system is also perfectly mixed, with an unchanging biomass of bacteria, and so there is no spatial resolution. This allows us to focus on the chemical reactions alone.

### Module resources {#M2_5 -}

Download the Excel spreadsheet: [MODULE02_Biogeochemistry.xlsx](./resources/module2/MODULE02_Biogeochemistry.xlsx)

Download the R scripts: [MODULE2_R_Biogeochem.zip](./resources/module2/MODULE2_R_Biogeochem.zip)

### Exercises {#M2_6 -}

#### Building the model in Excel {#M2_7 -}

1) Looking at the sequence of equations above: what is the difference between the limitation and the inhibition term? Have a good think about this. If concentration were amazingly bigger or smaller than the $K_{O_{x}}$^[Where $K_{O_{x}}$ is the general term for the half saturation constant of any oxidant, for example $K_{O_{2}}$, $K_{SO_{4}}$ etc.], what would happen to the rates of the higher and lower energy processes? For example, with a high oxygen concentration, what would happen to the manganese reduction rate? With a low oxygen and nitrate concentration, and a high manganese concentration, what would happen to the manganese oxidation rate?


2) Complete the excel spreadsheet for iron reduction, sulfate reduction and methanogenesis. Oxygen, nitrate and manganese are done already, so copy the method and use the equations at the tops of the columns. It is tedious, fiddly and there is a good chance that you will introduce bugs that are hard to find. This is the nature of Excel.

```{block2, hint3, type='rmdnote2'}
The rate is dependent on the concentration in the previous time step – this is called an *explicit* solution (as opposed to *implicit*).
```

3) Complete the line plot (**1**) of relative oxidant concentration for iron and sulphate. Right click on the plot and use ‘Add data’, make the x axis time and the y axis relative concentration. It is easy to visualise if you keep the colours consistent, and choose the colours that you like. Adjust the values for the initial condition and the half-saturation constants and see how the lines move on your plot. Add more time steps underneath if you want to see what happens over the long term.

4) Complete the area plot (**2**) of reaction rates, then play around with the numbers to test the sensitivities of the outputs to the parameter inputs

####  Building the model in R {#M2_8 -}

Now the excel spreadsheet is working, the next step is to repeat the process in R.

5) Open the R project and the three scripts: there is one in which you set the input parameters and initial conditions; one which has the equations; and one which is used for plotting the outputs. Read through them and become familiar with what is in each.

6) Run each script in sequence, starting with Inputs, then Equations, then Plotting. The plotting script should make a plot appear in the bottom right corner.

7) Enter the inputs, equations and plotting scripts for iron, sulfate and methanogenesis reactions, just as you did in the excel spreadsheet. Remember that you just need a rate of methanogenesis: methane is not an oxidant like sulfate.

8) In the Plotting script, uncomment (remove the #s) the lines starting with `png` and `dev.off`. Now if you run the plot (**3**) again, it saves the plot to a .png file. You can edit the settings of the png line to create a high quality figure to put in the report.

Now we have a working process-based model. This was the hard and boring part, but now we can be creative. So far we have established an initial condition and let it run to completion, but next we can model a hypothetical environmental situation. For example, imagine there were an oxygen fluctuation, perhaps from algal photosynthesis occurring in the day but not at night in a lake, or from the tidal movement of hypoxic water.

9) In either Excel or R, create a new environmental situation that involves organic matter oxidation. Consider the assumptions you are making and how important they are. Use the model to test the effect of this situation on concentrations and rates. For example, what would happen if there were regular organic matter deposition as a boundary condition? Or maybe what if there were a constant oxygen concentration? What conditions might be needed to minimise methanogenesis? How could you maximise denitrification? I will give higher marks if you do something original and creative. Write a brief description of your new situation and create one plot (**4**) to explain your result. 

### Submission {#M2_9 -}
:::: {.redbox2}

**Submit properly formatted graphs and tables of the following sections of the lab:**

- Graph of concentration (y) against time (x) scatter plot, for all oxidants, made in Excel
- Graph of rate (y) against time (x) area plot, for all oxidants
- Graph of concentration (y) against time (x) scatter plot, for all oxidants, made in R
- Any figure of a new environmental situation you create, and a brief explanation of lessthan 100 words of how you used the model creatively.

These are in a word doc or PDF format. No screenshots of figures from Excel/Excel spreadsheets to be uploaded

**General professional formatting guidelines:**

- All figures are to have adequate captions explaining them
- For graphs, figure captions go below the plot
- For tables, the caption goes above the table
- Make sure figures and their text size is readable

**Excel hints:**

- When there is a caption for a plot, you remove the title
- Remove the plot border and gridlines
- Make sure both axes have visible lines and tick marks
- Units need to be noted properly with the axis label - 'Temperature (°C)'
- Round numbers to be reasonable
::::

