# Exercise 2 - Sourcing rainfall and flow data {#E1B -}

## Introduction {#E1B_1 -}

The previous exercise focused on estimating rainfall and runoff at catchment scales during a single (daily) storm event.  This focused on catchment scale rainfall and processes.  In this exercise we will learn how to access rain and flow data, and examine the nature of rainfall data and use some simple statistics in Excel to describe these data.  This will help you prepare for the Assignment 1A where you will examine at how rainfall may be changing over time, how it varies over space across Western Australia, and how it correlates with flow.  


## Objective {#E1B_2 -}

By the end of this activity, you should:

- Be able to source rainfall and flow data, understand the nature of that data and describe it using simple statistics in Excel.


## Getting Rainfall Data {#E1B_3 -}


1) Start by downloading the daily rainfall data for a chosen BOM site from the [Bureau of Meteorology](http://www.bom.gov.au/climate/data/) web site. Choose a site of interest in Western Australia.  Use the site ID to get the data as below. Download and extract the zipped file to get a CSV file that can be opened in Excel. 

<center>
<video width="100%" height="100%" controls>
  <source src="images/exercise1A/video1.mp4" type="video/mp4">
</video>
</center>

## Statistical Properties of Rainfall Data {#E1B_4 -}

Before moving forward with our analysis lets open the dataset and make sure the site has a suitable period of data.

2) Now, let’s plot the time series of DAILY rainfall. Clean up the plot as required and add to your activity sheet. Describe the main features of this data set. Consider: what is the most appropriate type of graph for rainfall data (bar, scatter, line)?

3) Calculate the annual SUM of rainfall. But note, we want to ensure that there are only whole years to calculate the sums or else the incomplete years will be in error (the sum will be artificially low due to missing data). Delete the rows of data for the last partial year (e.g., 2021) and any partial years at the start (the first and last year measured may change depending on the site you selected). To explore each year's data we will use a PIVOT table. Select the required data across multiple columns (year C to rainfall amount F). Then insert PIVOT table (select "Create a new tab"). Select Year and Rainfall amount as the FIELDS. Drag the Year FIELD into the ROWS box. Left click on the “Sum of Year” in the VALUES box and remove it. Plot the annual sums as a timeseries. You can also select "COUNT" to see how many entries are given for each. Years with more than 10% of days missing (e.g <300 days counted), are unreliable to include in our analysis so see if your station has any incomplete years. Clean up the plot with the sum of rainfall as required and add to your activity sheet. What are the main features of this annual data set? What variability can you see? 


4) Now we have a "clean" dataset, we want to explore some statistics. Use the *Data Analysis* add-in to calculate descriptive statistics (mean annual rainfall, max annual rainfall, min annual rainfall, Standard deviation of annual rainfall, Skewness) for the whole data (you can install by going to *Tools->Add-ins->Analysis ToolPack*).
Copy the results [here](https://docs.google.com/spreadsheets/d/1gFbXF9USMM8nQghy1P0cIThnNT3TFadwFy2RstU41PA/edit?usp=sharing) and complete Table \@ref(tab:E1Btable1) for your site (and others when they are done). Describe the values you got and what they mean. How “useful” are these statistics for your understanding of the system? What if any assumptions are there about these statistics? 

<!-- Old link: -->
<!-- https://docs.google.com/spreadsheets/d/10mHrNWEHoqWif96e7SwvowfQ7sMg_qMxFtw6POr7sG4/edit?usp=sharing -->

5) Next, let’s look at the distribution of the rainfall data. Do this by plotting a histogram of the rainfall data (you will need to decide on a reasonable bin size) and plotting the cumulative probability distribution (you can ask Excel to generate this automatically when it makes the histogram, or generate it manually – each data point represents a probability of 1/#data points). What do these plots tell you about the rainfall data? Are the data normally distributed? 

6) Plot the seasonal (monthly average) rainfall. Use a PIVOT table again. Insert PIVOT table (select OK to create a new tab). Select **Month** and **Rainfall** amount as the FIELDS; drag the Month FIELD into the ROWS box. Left click on the “Sum of Month” in the VALUES box and remove it. Plot the annual sums as a timeseries. Clean up the plot as required and submit on your answer sheet.
How would you describe the seasonal pattern of rainfall (hint look at the climate type)? What factors may influence it (hint, think about earth orbit)? 

<center>
```{r E1Btable1, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
options(kableExtra.html.bsTable = F, knitr.kable.NA = '')
table1.csv <- read.csv("tables/exercise1B/table1.csv", check.names=FALSE)
kable(table1.csv,"html", escape = F, align = rep('c', 5), caption = "Bureau of Meteorology Automatic Weather Station data and station ID across WA and SWWA. Complete a row in the table for your site [here](https://docs.google.com/spreadsheets/d/1gFbXF9USMM8nQghy1P0cIThnNT3TFadwFy2RstU41PA/edit?usp=sharing).",
      bootstrap_options = "hover") %>%
  kable_styling(table1.csv, bootstrap_options = "hover", "striped",
                full_width = F, position = "center",
                font_size = 12) %>%
  column_spec(1, width_min = "10em") %>%
  column_spec(2, width_min = "10em") %>%
  column_spec(3, width_min = "10em") %>%
  column_spec(4, width_min = "10em") %>%
  column_spec(5, width_min = "10em") %>%
  column_spec(6, width_min = "10em") %>%
  row_spec(1:25, background = 'white') %>%
  scroll_box(width = "100%", height = "515px",
             fixed_thead = FALSE)
```
</center>

## Getting Streamflow Data {#E1B_5 -}

7) In your Assessment 1A we will need to examine the relationship between annual rainfall and annual streamflow (aka runoff) for a chosen catchment. Streamflow data is recently reported on the BOM website for some rivers, but the measurement of streamflow is a State Government responsibility. To get streamflow data, go the [Department of Water](http://wir.water.wa.gov.au/Pages/Water-Information-Reporting.aspx) web site. Use this WIR tool to locate a gauging station near your rainfall site. Add the site to your cart and submit a data request - check that the data is being delivered as a "package of pre-computed reports". You will then be emailed a zip file of the station's data. Ensure the station has 10-20 years of available data for this exercise.

<center>
<video width="85%" height="85%" controls>
<source src="images/exercise1B/video1.mp4" type="video/mp4">
</video>
</center>

8) Once you have the data, explore the CSV file received to see the nature of the data provided - i.e., river flow discharge rate. Can you use the techniques introduced above to summarise the data (e.g., create a PIVOT table)?

## Conclusions  {#E1B_6 -}

Now you know how to source some essential water data, and summarise it in an easy to use fashion. What else could we do to explore the data?
