--- 
title: "Hydrology Workbook"
author: "Matt Hipsey, Sarah Bourke, Jason Beringer and Giles Knight"
date: "Last updated: `r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:  ["references/references.bib"]
biblio-style: apalike
link-citations: true
description: ""
---

# Introduction {-}

## Overview {#AI_2 .unnumbered}

This site is a web-based "workbook" containing instructions and information needed to undertake the activities and assessments in **ENVT2251 Hydrology and Water Resource Management** unit at UWA. 

The workbook is broken up into 3 types of activities:

-   **Exercises**: non-assessed desktop-based activities, to be undertaken either self-paced or in-class workshops.
-   **Labs**: Practical activities to be undertaken in the lab or field sessions as guided by teaching staff.
-   **Assessments**: Specific instructions for assessed activities.
 
Note that work undertaken in the exercises maybe referred to in the unit quiz assessments, or form the foundation of tasks required in the assessments. 

The module specific activities will be updated sequentially throughout semester.  

## Recommended study plan {#AI_2 .unnumbered}

From the below table you can see the weekly activities, and the links between the workbook and the over-arching LMS modules.

```{r, echo=FALSE}
htmltools::includeHTML("tables/intro/table1.html")
```

## Further information {#AI_32 .unnumbered}

Please refer to the ENVT2251 LMS pages for information about the course schedule and for accessing lecture content. For more information contact your Unit Coordinator or tutor.